services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/nova-ecommerce
      UPSTASH_REDIS_URL: redis://redis:6379
      CLIENT_URL: http://localhost:5000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine

volumes:
  mongo_data:
